Repository ConnectPlus-Org/ConnectPlus-Frontend, pull requests merged in 2023-10, with the labels that each got.

#31 Bug Fixed: password validation
  src/Authentication/login/LoginApp.tsx
  src/Authentication/reset password/resetPassApp.tsx
  src/Authentication/set password/setPassApp.tsx
Labels: hacktoberfest

#39 Added callToAction for comment in post on homepage
  src/homepage/homepage.css
  src/homepage/post.tsx
Labels: bug, good first issue, hacktoberfest, Hacktoberfest-accepted

#49 applied camelcasing
  src/Authentication/Signup/SignUpApp.tsx
  src/Authentication/Signup/signup.tsx
  src/Authentication/forgot/forgotAPP.tsx
  src/Authentication/login/LoginApp.tsx
  src/Authentication/otp/emailotpapp.tsx
  src/Authentication/otp/phoneotpapp.tsx
  src/Authentication/profile creation/profileHead.tsx
  src/Authentication/reset password/resetPassApp.tsx
  src/Authentication/set password/setPassApp.tsx
  src/MyAccount/AboutMe/aboutMeApp.tsx
  src/MyAccount/Additional/courses.tsx
  src/MyAccount/Additional/score.tsx
  src/MyAccount/Education/Education.tsx
  src/MyAccount/Main/MainApp.tsx
  src/MyAccount/edit_profile/edit_profile.tsx
  src/MyAccount/edit_profile/experience.tsx
  src/homepage/comment.tsx
  src/homepage/createpost.css
  src/homepage/createpost.tsx
  src/homepage/homepage.css
  src/homepage/homepage.tsx
  src/homepage/post.tsx
  src/homepage/saved.tsx
  src/loader.tsx
  src/network/components/connectioncomponent.tsx
  src/network/components/followercomponent.tsx
  src/network/components/followingcomponent.tsx
  src/network/components/recievedcomponent.tsx
  src/network/components/sentcomponent.tsx
  src/network/network.css
  src/spinner.css
Labels: enhancement, good first issue, hacktoberfest, Hacktoberfest-accepted
